# Generated by Django 2.2.5 on 2019-09-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nomeFantasia',
            new_name='nome',
        ),
    ]
